version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/roadside-forms-frontend/frontend_web_app"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/python/prohibition_web_svc"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    open-pull-requests-limit: 5
