name: db-migrate-workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
      checkout_branch:
        required: true
        type: string
  push:
    branches:
      - patch/dbmigrate
    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      checkout_branch: db-migrate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
        #   ref: ${{ inputs.checkout_branch }}
          ref: ${{ env.checkout_branch }}

    #   - name: Setup
    #     uses: docker/setup-buildx-action@v2
    #     with:
    #       install: true

    #   - name: Login
    #     uses: docker/login-action@v2
    #     with:
    #       registry: ${{ secrets.DOCKER_REGISTRY }}
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Tag
    #     id: tag
    #     uses: mathieudutour/github-tag-action@v6.1
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       tag_prefix: ${{ inputs.DOCKER_IMAGE_NAME }}=v
    #       fetch_all_tags: true

    #   - name: Build
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: ${{ inputs.DOCKER_CONTEXT }}
    #       file: ${{ inputs.DOCKER_FILE }}
    #       push: true
    #       tags: ${{ secrets.DOCKER_REGISTRY }}/dbe7-images/${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.DOCKER_IMAGE_TAG }}